Repository asarkar/build-time-tracker, pull requests merged in 2020-07, with the labels that each got.

#4 Fix #1, #2, #3
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  README.md
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/Constants.kt
  gradle.properties
  settings.gradle.kts
  src/main/kotlin/org/asarkar/gradle/BuildTimeTrackerPlugin.kt
  src/main/kotlin/org/asarkar/gradle/ConsolePrinter.kt
  src/main/kotlin/org/asarkar/gradle/Constants.kt
  src/main/kotlin/org/asarkar/gradle/Printer.kt
  src/main/kotlin/org/asarkar/gradle/TimingRecorder.kt
  src/test/kotlin/org/asarkar/gradle/BuildTimeTrackerPluginFunctionalTest.kt
  src/test/kotlin/org/asarkar/gradle/ConsolePrinterTest.kt
Labels: bug, enhancement

#7 Fix #4: standardize durations
  README.md
  gradle.properties
  src/main/kotlin/org/asarkar/gradle/BuildTimeTrackerPlugin.kt
  src/main/kotlin/org/asarkar/gradle/ConsolePrinter.kt
  src/main/kotlin/org/asarkar/gradle/TimingRecorder.kt
  src/test/kotlin/org/asarkar/gradle/BuildTimeTrackerPluginFunctionalTest.kt
  src/test/kotlin/org/asarkar/gradle/ConsolePrinterTest.kt
Labels: enhancement

#11 Fix #4: NoClassDefFoundError: kotlin/time/TimeSource$Monotonic
  gradle.properties
  src/main/kotlin/org/asarkar/gradle/ConsolePrinter.kt
  src/main/kotlin/org/asarkar/gradle/Printer.kt
  src/main/kotlin/org/asarkar/gradle/TimingRecorder.kt
  src/test/kotlin/org/asarkar/gradle/ConsolePrinterTest.kt
Labels: bug

#9 Fix #8: Support Java 8
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  README.md
  build.gradle.kts
Labels: enhancement, good first issue, help wanted

#13 Fix #12: Compilation failure on Java 8
  .github/workflows/ci.yml
  src/main/kotlin/org/asarkar/gradle/TimingRecorder.kt
  src/test/kotlin/org/asarkar/gradle/BuildTimeTrackerPluginFunctionalTest.kt
Labels: bug

#15 Fix #14: Remove deprecated API usage
  .github/workflows/ci.yml
  gradle.properties
  src/main/kotlin/org/asarkar/gradle/TimingRecorder.kt
Labels: enhancement
